name:           Clear Sans Webfont
description:    Webfont conversion of the Clear Sans typeface designed by Intel.

permalink:      pretty
highlighter:    pygments
url:            http://dasklney.github.io/Clear-Sans-Webfont
baseurl:        /Clear-Sans-Webfont/
exclude:        ["Makefile", "README.md", "less", "node_modules", "package.json"]
author:
  name:           Nguyen Truong Giang
  url:            http://dasklney.github.io
  email:          dasklney@giang.us
